version: '3.9'

services:
  driver_behavior_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: driver_behavior_api
    ports:
      - "8890:8890"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
